# SPDX-License-Identifier: GPL-2.0-only

obj-$(CONFIG_UWE5622_CORE) += uwe5622_core.o
uwe5622_core-y := bind.o core.o sdio.o

obj-$(CONFIG_UWE5622_WIFI) += uwe5622_wifi.o
uwe5622_wifi-y := wifi.o wifi_cmd.o
